export const getHospitalsByLocation = async (location) => {
  // This is mock data. In a real application, you would fetch this from a database or external API.
  const mockHospitals = [
    {
      id: 'hosp1',
      name: 'City General Hospital',
      address: '123 Main St, Downtown, New York, USA',
      phone: '+1-111-222-3333',
      website: 'http://citygeneral.com',
      specialties: ['Emergency', 'Cardiology', 'Pediatrics'],
      rating: 4.5,
    },
    {
      id: 'hosp2',
      name: 'Community Health Center',
      address: '456 Oak Ave, Central, London, UK',
      phone: '+1-444-555-6666',
      website: 'http://communityhealth.org',
      specialties: ['General Practice', 'Dermatology', 'Internal Medicine'],
      rating: 4.2,
    },
    {
      id: 'hosp3',
      name: 'Riverside Medical Center',
      address: '789 River Rd, Riverside, Sydney, Australia',
      phone: '+1-777-888-9999',
      website: 'http://riversidemed.net',
      specialties: ['Neurology', 'Oncology'],
      rating: 4.7,
    },
    {
      id: 'hosp4',
      name: 'Parkview Hospital',
      address: '101 Park Blvd, Park Avenue, Toronto, Canada',
      phone: '+1-222-333-4444',
      website: 'http://parkviewhosp.org',
      specialties: ['Orthopedics', 'Physical Therapy'],
      rating: 4.0,
    },
    {
      id: 'hosp5',
      name: 'Elite Surgical Center',
      address: '202 High St, Downtown, Paris, France',
      phone: '+1-999-000-1111',
      website: 'http://elitesurgery.com',
      specialties: ['Surgery', 'Anesthesiology'],
      rating: 4.9,
    },
    // Hospitals in India (Andhra Pradesh and Telangana)
    {
      id: 'hosp6',
      name: 'Apollo Hospitals Hyderabad',
      address: 'Jubilee Hills, Hyderabad, Telangana, India',
      phone: '+91-40-2360-7777',
      website: 'http://apollohospitals.com/hyderabad',
      specialties: ['Multi-specialty', 'Cardiology', 'Oncology'],
      rating: 4.8,
    },
    {
      id: 'hosp7',
      name: 'Yashoda Hospitals Secunderabad',
      address: 'Secunderabad, Telangana, India',
      phone: '+91-40-4567-4567',
      website: 'http://yashodahospitals.com',
      specialties: ['Multi-specialty', 'Neurology', 'Gastroenterology'],
      rating: 4.6,
    },
    {
      id: 'hosp8',
      name: 'KIMS Hospitals Secunderabad',
      address: 'Minister Road, Secunderabad, Telangana, India',
      phone: '+91-40-4418-6000',
      website: 'http://kimshospitals.com',
      specialties: ['Multi-specialty', 'Orthopedics', 'Nephrology'],
      rating: 4.7,
    },
    {
      id: 'hosp9',
      name: 'Continental Hospital',
      address: 'Gachibowli, Hyderabad, Telangana, India',
      phone: '+91-40-6700-0000',
      website: 'http://continentalhospitals.com',
      specialties: ['Multi-specialty', 'Transplant', 'Critical Care'],
      rating: 4.5,
    },
    // Hospitals in Hyderabad Districts
    {
      id: 'hosp21',
      name: 'MaxCure Hospitals',
      address: 'Madhapur, Hyderabad, Telangana, India',
      phone: '+91-40-4400-0000',
      website: 'http://maxcurehospitals.com',
      specialties: ['Multi-specialty', 'Cardiology', 'Orthopedics'],
      rating: 4.4,
    },
    {
      id: 'hosp22',
      name: 'Sunshine Hospitals',
      address: 'Secunderabad, Hyderabad, Telangana, India',
      phone: '+91-40-4455-5555',
      website: 'http://sunshinehospitals.com',
      specialties: ['Multi-specialty', 'Orthopedics', 'Plastic Surgery'],
      rating: 4.3,
    },
    {
      id: 'hosp23',
      name: 'Aster Prime Hospital',
      address: 'Ameerpet, Hyderabad, Telangana, India',
      phone: '+91-40-2345-0100',
      website: 'http://asterprime.com',
      specialties: ['Multi-specialty', 'Neurology', 'Nephrology'],
      rating: 4.6,
    },
    {
      id: 'hosp24',
      name: 'Ojas Hospital',
      address: 'Nallakunta, Hyderabad, Telangana, India',
      phone: '+91-40-2766-7788',
      website: 'N/A',
      specialties: ['General Medicine', 'Pediatrics'],
      rating: 4.0,
    },
    {
      id: 'hosp25',
      name: 'Care Hospitals',
      address: 'Banjara Hills, Hyderabad, Telangana, India',
      phone: '+91-40-3041-8888',
      website: 'http://carehospitals.com',
      specialties: ['Multi-specialty', 'Cardiology', 'Gastroenterology'],
      rating: 4.7,
    },
    {
      id: 'hosp26',
      name: 'Basavatarakam Indo American Cancer Hospital & Research Institute',
      address: 'Banjara Hills, Hyderabad, Telangana, India',
      phone: '+91-40-2355-1234',
      website: 'http://indoamericancancer.com',
      specialties: ['Oncology', 'Cancer Research'],
      rating: 4.9,
    },
    {
      id: 'hosp27',
      name: 'Gleneagles Global Hospital',
      address: 'Lakdi-ka-pul, Hyderabad, Telangana, India',
      phone: '+91-40-3369-9999',
      website: 'http://gleneaglesglobalhospitals.com',
      specialties: ['Multi-specialty', 'Organ Transplant', 'Cardiac Sciences'],
      rating: 4.5,
    },
    {
      id: 'hosp28',
      name: 'Virinchi Hospitals',
      address: 'Banjara Hills, Hyderabad, Telangana, India',
      phone: '+91-40-4699-9999',
      website: 'http://virinchihospitals.com',
      specialties: ['Multi-specialty', 'Critical Care', 'Neurosciences'],
      rating: 4.4,
    },
    {
      id: 'hosp29',
      name: 'Apollo Cradle & Children’s Hospital',
      address: 'Kondapur, Hyderabad, Telangana, India',
      phone: '+91-40-4242-4242',
      website: 'http://apollocradle.com',
      specialties: ['Pediatrics', 'Maternity'],
      rating: 4.6,
    },
    {
      id: 'hosp30',
      name: 'Rainbow Children’s Hospital',
      address: 'Banjara Hills, Hyderabad, Telangana, India',
      phone: '+91-40-4060-5000',
      website: 'http://rainbowhospitals.in',
      specialties: ['Pediatrics', 'Maternity', 'Neonatology'],
      rating: 4.8,
    },
    {
      id: 'hosp10',
      name: 'Medicover Hospitals Vizag',
      address: 'Ram Nagar, Visakhapatnam, Andhra Pradesh, India',
      phone: '+91-891-6788-888',
      website: 'http://medicoverhospitals.in/vizag',
      specialties: ['Multi-specialty', 'Cardiology', 'Urology'],
      rating: 4.3,
    },
    {
      id: 'hosp11',
      name: 'King George Hospital (KGH)',
      address: 'Maharanipeta, Visakhapatnam, Andhra Pradesh, India',
      phone: '+91-891-270-4315',
      website: 'N/A',
      specialties: ['General', 'Emergency'],
      rating: 3.9,
    },
    {
      id: 'hosp12',
      name: 'Narayana Medical College Hospital',
      address: 'Nellore, Andhra Pradesh, India',
      phone: '+91-861-230-0700',
      website: 'http://narayanahealth.org',
      specialties: ['Multi-specialty', 'Cardiology', 'Neurology'],
      rating: 4.4,
    },
    {
      id: 'hosp13',
      name: 'Manipal Hospitals Vijayawada',
      address: 'Gollapudi, Vijayawada, Andhra Pradesh, India',
      phone: '+91-866-255-0000',
      website: 'http://manipalhospitals.com/vijayawada',
      specialties: ['Multi-specialty', 'Oncology', 'Gastroenterology'],
      rating: 4.6,
    },
    // Hospitals in Andhra Pradesh Cities/Districts
    {
      id: 'hosp31',
      name: 'Ramesh Hospitals',
      address: 'Ring Road, Vijayawada, Andhra Pradesh, India',
      phone: '+91-866-255-0000',
      website: 'http://rameshhospitals.com',
      specialties: ['Cardiology', 'Neurosciences', 'Emergency'],
      rating: 4.7,
    },
    {
      id: 'hosp32',
      name: 'NTR University of Health Sciences Hospital',
      address: 'Gunadala, Vijayawada, Andhra Pradesh, India',
      phone: '+91-866-245-1393',
      website: 'http://ntruhs.ap.nic.in',
      specialties: ['General Medicine', 'Medical Education'],
      rating: 4.0,
    },
    {
      id: 'hosp33',
      name: 'Guntur Medical College Hospital',
      address: 'Guntur, Andhra Pradesh, India',
      phone: '+91-863-222-0000',
      website: 'N/A',
      specialties: ['General Medicine', 'Pediatrics', 'Surgery'],
      rating: 4.2,
    },
    {
      id: 'hosp34',
      name: 'NRI General Hospital',
      address: 'Chinakakani, Mangalagiri Mandal, Guntur, Andhra Pradesh, India',
      phone: '+91-8645-231-180',
      website: 'http://nrihospital.com',
      specialties: ['Multi-specialty', 'Nephrology', 'Urology'],
      rating: 4.5,
    },
    {
      id: 'hosp35',
      name: 'Apollo Hospital',
      address: 'Chittoor, Andhra Pradesh, India',
      phone: '+91-8572-230-000',
      website: 'http://apollohospitals.com',
      specialties: ['Multi-specialty'],
      rating: 4.3,
    },
    {
      id: 'hosp36',
      name: 'SVIMS Hospital (Sri Venkateswara Institute of Medical Sciences)',
      address: 'Alipiri Road, Tirupati, Andhra Pradesh, India',
      phone: '+91-877-228-7777',
      website: 'http://svimstpt.ap.nic.in',
      specialties: ['Multi-specialty', 'Cardiology', 'Neurosciences', 'Oncology'],
      rating: 4.8,
    },
    {
      id: 'hosp37',
      name: 'Government General Hospital',
      address: 'Kakinada, East Godavari, Andhra Pradesh, India',
      phone: '+91-884-237-7777',
      website: 'N/A',
      specialties: ['General Medicine', 'Emergency'],
      rating: 3.8,
    },
    {
      id: 'hosp38',
      name: 'Pradhan Hospital',
      address: 'Rajahmundry, East Godavari, Andhra Pradesh, India',
      phone: '+91-883-247-7777',
      website: 'N/A',
      specialties: ['Multi-specialty', 'Orthopedics'],
      rating: 4.1,
    },
    {
      id: 'hosp39',
      name: 'Siddhartha Medical College Hospital',
      address: 'Ring Road, Kurnool, Andhra Pradesh, India',
      phone: '+91-8518-285-000',
      website: 'N/A',
      specialties: ['General Medicine', 'Medical Education'],
      rating: 4.0,
    },
    {
      id: 'hosp40',
      name: 'Government General Hospital',
      address: 'Kadapa, Andhra Pradesh, India',
      phone: '+91-8562-244-000',
      website: 'N/A',
      specialties: ['General Medicine', 'Emergency'],
      rating: 3.7,
    },
    {
      id: 'hosp41',
      name: 'Visakha Institute of Medical Sciences (VIMS)',
      address: 'Maharanipeta, Visakhapatnam, Andhra Pradesh, India',
      phone: '+91-891-278-2782',
      website: 'N/A',
      specialties: ['Multi-specialty', 'Cardiology', 'Nephrology'],
      rating: 4.2,
    },
    {
      id: 'hosp42',
      name: 'Sri Kanya Hospital',
      address: 'Gajuwaka, Visakhapatnam, Andhra Pradesh, India',
      phone: '+91-891-255-5555',
      website: 'N/A',
      specialties: ['General Medicine', 'Pediatrics'],
      rating: 4.0,
    },
    {
      id: 'hosp20',
      name: 'MIOT International',
      address: 'Mount Poonamalle Road, Manapakkam, Chennai, Tamil Nadu, India',
      phone: '+91-44-4200-2288',
      website: 'http://miotinternational.com',
      specialties: ['Multi-specialty', 'Orthopedics', 'Cardiothoracic', 'Transplants'],
      rating: 4.7,
    },
    // Hospitals in Chennai Districts/Areas
    {
      id: 'hosp43',
      name: 'SIMS Hospital (SRM Institutes for Medical Science)',
      address: 'No. 1, Jawaharlal Nehru Salai, Vadapalani, Chennai, Tamil Nadu, India',
      phone: '+91-44-2000-2000',
      website: 'http://simshospitals.com',
      specialties: ['Multi-specialty', 'Cardiology', 'Oncology', 'Neuroscience'],
      rating: 4.5,
    },
    {
      id: 'hosp44',
      name: 'Madras Medical College & Government General Hospital',
      address: 'EVR Periyar Salai, Park Town, Chennai, Tamil Nadu, India',
      phone: '+91-44-2530-5000',
      website: 'N/A',
      specialties: ['General', 'Emergency', 'Medical Education'],
      rating: 4.0,
    },
    {
      id: 'hosp45',
      name: 'Kauvery Hospital',
      address: 'No.1, Lady Desika Road, Mylapore, Chennai, Tamil Nadu, India',
      phone: '+91-44-4000-6000',
      website: 'http://kauveryhospital.com',
      specialties: ['Multi-specialty', 'Cardiology', 'Gastroenterology'],
      rating: 4.6,
    },
    {
      id: 'hosp46',
      name: 'Billroth Hospitals',
      address: 'No. 43, 2nd Main Road, R.A. Puram, Chennai, Tamil Nadu, India',
      phone: '+91-44-2464-1111',
      website: 'http://billrothhospitals.com',
      specialties: ['Multi-specialty', 'Orthopedics', 'Nephrology'],
      rating: 4.3,
    },
    {
      id: 'hosp47',
      name: 'Vijaya Hospital',
      address: 'No. 180, N.S.K. Salai, Vadapalani, Chennai, Tamil Nadu, India',
      phone: '+91-44-2472-2266',
      website: 'http://vijayahospital.in',
      specialties: ['Multi-specialty', 'Cardiology', 'Neurology'],
      rating: 4.4,
    },
    {
      id: 'hosp48',
      name: 'SRM Institutes for Medical Science (SRM SIMS)',
      address: 'Grand Southern Trunk Road, Kattankulathur, Chennai, Tamil Nadu, India',
      phone: '+91-44-2745-7777',
      website: 'http://srmist.edu.in/medical-college',
      specialties: ['Multi-specialty', 'Medical Education', 'Research'],
      rating: 4.2,
    },
    {
      id: 'hosp49',
      name: 'Global Hospital',
      address: '439, Cheran Nagar, Perumbakkam, Chennai, Tamil Nadu, India',
      phone: '+91-44-2277-7000',
      website: 'http://globalhospitals.in',
      specialties: ['Multi-organ Transplant', 'Liver Disease', 'Gastroenterology'],
      rating: 4.7,
    },
    {
      id: 'hosp50',
      name: 'Apollo Spectra Hospitals',
      address: 'Kotturpuram, Chennai, Tamil Nadu, India',
      phone: '+91-44-4244-4444',
      website: 'http://apollospectra.com',
      specialties: ['Multi-specialty', 'Day Surgery'],
      rating: 4.5,
    },
    {
      id: 'hosp51',
      name: 'Chettinad Hospital & Research Institute',
      address: 'Kelambakkam, Chennai, Tamil Nadu, India',
      phone: '+91-44-4742-9999',
      website: 'http://chettinadhospital.com',
      specialties: ['Multi-specialty', 'Medical Education', 'Research'],
      rating: 4.1,
    },
    {
      id: 'hosp52',
      name: "Child's Trust Hospital", // Changed to double quotes to fix SyntaxError
      address: 'Nungambakkam, Chennai, Tamil Nadu, India',
      phone: '+91-44-4200-1800',
      website: 'http://childstrust.in',
      specialties: ['Pediatrics', 'Neonatology'],
      rating: 4.8,
    },
    {
      id: 'hosp53',
      name: 'Hande Hospital',
      address: 'Nungambakkam, Chennai, Tamil Nadu, India',
      phone: '+91-44-2827-1425',
      website: 'N/A',
      specialties: ['General Medicine', 'Orthopedics'],
      rating: 4.0,
    },
    // Hospitals in Karnataka State (Districts & Cities)
    {
      id: 'hosp54',
      name: 'Apollo Hospitals Bannerghatta',
      address: 'Bannerghatta Road, Bengaluru, Karnataka, India',
      phone: '+91-80-2630-4050',
      website: 'http://apollohospitals.com/bengaluru',
      specialties: ['Multi-specialty', 'Cardiology', 'Neuroscience', 'Oncology'],
      rating: 4.8,
    },
    {
      id: 'hosp55',
      name: 'Manipal Hospital Old Airport Road',
      address: 'Old Airport Road, Bengaluru, Karnataka, India',
      phone: '+91-80-2502-4444',
      website: 'http://manipalhospitals.com/bengaluru',
      specialties: ['Multi-specialty', 'Organ Transplant', 'Gastroenterology'],
      rating: 4.7,
    },
    {
      id: 'hosp56',
      name: 'Fortis Hospital Cunningham Road',
      address: 'Cunningham Road, Bengaluru, Karnataka, India',
      phone: '+91-80-2502-3400',
      website: 'http://fortishealthcare.com/bengaluru',
      specialties: ['Multi-specialty', 'Cardiac Sciences', 'Orthopedics'],
      rating: 4.6,
    },
    {
      id: 'hosp57',
      name: 'Aster CMI Hospital',
      address: 'Sahakar Nagar, Bengaluru, Karnataka, India',
      phone: '+91-80-4660-0000',
      website: 'http://asterdmhealthcare.com/hospitals/aster-cmi-hospital',
      specialties: ['Multi-specialty', 'Pediatrics', 'Robotic Surgery'],
      rating: 4.7,
    },
    {
      id: 'hosp58',
      name: 'Columbia Asia Hospital',
      address: 'Sarjapur Road, Bengaluru, Karnataka, India',
      phone: '+91-80-6644-6644',
      website: 'http://columbiaasia.com/hospitals/india/bengaluru/sarjapur-road',
      specialties: ['Multi-specialty', 'Emergency'],
      rating: 4.5,
    },
    {
      id: 'hosp59',
      name: 'Narayana Health City',
      address: 'Bommasandra, Bengaluru, Karnataka, India',
      phone: '+91-80-6750-6750',
      website: 'http://narayanahealth.org/hospitals/bengaluru/narayana-health-city',
      specialties: ['Cardiac Sciences', 'Oncology', 'Nephrology', 'Pediatrics'],
      rating: 4.9,
    },
    {
      id: 'hosp60',
      name: 'KMC Hospital (Manipal Teaching Hospital)',
      address: 'Jyothi Nagar, Mangalore, Karnataka, India',
      phone: '+91-824-222-5000',
      website: 'http://kmchospitalmangalore.com',
      specialties: ['Multi-specialty', 'Medical Education'],
      rating: 4.4,
    },
    {
      id: 'hosp61',
      name: 'Indiana Hospital & Heart Institute',
      address: 'Mahaveer Circle, Kankanady, Mangalore, Karnataka, India',
      phone: '+91-824-288-0000',
      website: 'http://indianahospital.in',
      specialties: ['Cardiology', 'Cardiothoracic Surgery', 'Urology'],
      rating: 4.6,
    },
    {
      id: 'hosp62',
      name: 'Vikram Hospital',
      address: 'Millennium, Jayalakshmipuram, Mysore, Karnataka, India',
      phone: '+91-821-400-0000',
      website: 'http://vikramhospital.com',
      specialties: ['Multi-specialty', 'Neuroscience', 'Cardiology'],
      rating: 4.5,
    },
    {
      id: 'hosp63',
      name: 'Columbia Asia Hospital Mysore',
      address: 'Industrial Layout, Hebbal, Mysore, Karnataka, India',
      phone: '+91-821-398-0000',
      website: 'http://columbiaasia.com/hospitals/india/mysore',
      specialties: ['Multi-specialty', 'Orthopedics', 'General Surgery'],
      rating: 4.4,
    },
    {
      id: 'hosp64',
      name: 'S.D.M. College of Medical Sciences & Hospital',
      address: 'Manjushree Nagar, Sattur, Dharwad, Karnataka, India',
      phone: '+91-836-247-7000',
      website: 'http://sdmmedical.org',
      specialties: ['Multi-specialty', 'Medical Education'],
      rating: 4.2,
    },
    {
      id: 'hosp65',
      name: 'Karnataka Institute of Medical Sciences (KIMS)',
      address: 'Vidyanagar, Hubballi, Karnataka, India',
      phone: '+91-836-227-8000',
      website: 'N/A',
      specialties: ['General Medicine', 'Emergency', 'Teaching Hospital'],
      rating: 3.9,
    },
    // Hospitals in India (Major Capital Cities / States)
    {
      id: 'hosp66',
      name: 'Apollo Hospitals Mumbai',
      address: 'Parsik Hill Road, Off Belapur Road, CBD Belapur, Navi Mumbai, Maharashtra, India',
      phone: '+91-22-6280-6280',
      website: 'http://apollohospitals.com/mumbai',
      specialties: ['Multi-specialty', 'Cardiology', 'Oncology', 'Transplants'],
      rating: 4.7,
    },
    {
      id: 'hosp67',
      name: 'Kokilaben Dhirubhai Ambani Hospital',
      address: 'Rao Saheb Achutrao Patwardhan Marg, Four Bungalows, Andheri West, Mumbai, Maharashtra, India',
      phone: '+91-22-3069-6969',
      website: 'http://kokilabenhospital.com',
      specialties: ['Multi-specialty', 'Cancer', 'Neuroscience', 'Heart Institute'],
      rating: 4.8,
    },
    {
      id: 'hosp68',
      name: 'Max Healthcare Hospital',
      address: '1, 2, Press Enclave Road, Saket, New Delhi, Delhi, India',
      phone: '+91-11-2651-5050',
      website: 'http://maxhealthcare.in',
      specialties: ['Multi-specialty', 'Cardiac Sciences', 'Orthopedics', 'Oncology'],
      rating: 4.6,
    },
    {
      id: 'hosp69',
      name: 'Fortis Escorts Heart Institute',
      address: 'Okhla Road, Sukhdev Vihar, New Delhi, Delhi, India',
      phone: '+91-11-2682-5000',
      website: 'http://fortisescortsheartinstitute.com',
      specialties: ['Cardiology', 'Cardiac Surgery'],
      rating: 4.7,
    },
    {
      id: 'hosp70',
      name: 'Apollo Gleneagles Hospitals',
      address: '58, Canal Circular Road, Kadapara, Phool Bagan, Kankurgachi, Kolkata, West Bengal, India',
      phone: '+91-33-2320-3040',
      website: 'http://apolloglengales.in',
      specialties: ['Multi-specialty', 'Cardiology', 'Oncology', 'Neuroscience'],
      rating: 4.5,
    },
    {
      id: 'hosp71',
      name: 'AMRI Hospitals',
      address: 'P-4 & 5, Gariahat Road, Dhakuria, Kolkata, West Bengal, India',
      phone: '+91-33-6680-0000',
      website: 'http://amrihospitals.in',
      specialties: ['Multi-specialty', 'Critical Care', 'Orthopedics'],
      rating: 4.4,
    },
    {
      id: 'hosp72',
      name: 'Fortis Escorts Hospital',
      address: 'Malviya Nagar, Jaipur, Rajasthan, India',
      phone: '+91-141-275-1515',
      website: 'http://fortishealthcare.com/jaipur',
      specialties: ['Multi-specialty', 'Cardiac Sciences', 'Kidney Transplant'],
      rating: 4.6,
    },
    {
      id: 'hosp73',
      name: 'Eternal Hospital',
      address: 'JLN Marg, Malviya Nagar, Jaipur, Rajasthan, India',
      phone: '+91-141-517-4000',
      website: 'http://eternalhospital.com',
      specialties: ['Multi-specialty', 'Cardiology', 'Oncology', 'Orthopedics'],
      rating: 4.5,
    },
  ];

  const lowerCaseLocation = location.toLowerCase();

  return new Promise((resolve) => {
    setTimeout(() => {
      const filteredHospitals = mockHospitals.filter(hospital =>
        hospital.address.toLowerCase().includes(lowerCaseLocation) ||
        hospital.name.toLowerCase().includes(lowerCaseLocation) ||
        hospital.specialties.some(s => s.toLowerCase().includes(lowerCaseLocation))
      );
      resolve(filteredHospitals);
    }, 500); // Simulate network delay
  });
};
